class Report < ApplicationRecord
  belongs_to :student

  validates_presence_of :init_date, presence: true, message: 'can t be left blank'
  validates_presence_of :end_date, presence: true, message: 'can t be left blank'
  validates_presence_of :school_phone, presence: true, message: 'can t be left blank'
  validates_presence_of :member_name, presence: true, message: 'can t be left blank'
  validates_presence_of :school_name, presence: true, message: 'can t be left blank'
  validates_presence_of :reason, presence: true, message: 'can t be left blank'
  validates_presence_of :general_information, presence: true, message: 'can t be left blank'
  validates_presence_of :synthesis, presence: true, message: 'can t be left blank'
  validates_presence_of :conclusion, presence: true, message: 'can t be left blank'
  validates_presence_of :family_orientation, presence: true, message: 'can t be left blank'
  validates_presence_of :school_orientation, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_name, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_function, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_registry, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_name, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_function, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_registry, presence: true, message: 'can t be left blank'
  validates_presence_of :reason_adequation, presence: true, message: 'can t be left blank'
  validates_presence_of :reason_emotional, presence: true, message: 'can t be left blank'
  validates_presence_of :reason_performance, presence: true, message: 'can t be left blank'
  validates_presence_of :reason_behavior, presence: true, message: 'can t be left blank'
  validates_presence_of :reason_language, presence: true, message: 'can t be left blank'
  validates_presence_of :level_school, presence: true, message: 'can t be left blank'
  validates_presence_of :level_family, presence: true, message: 'can t be left blank'
  validates_presence_of :level_student, presence: true, message: 'can t be left blank'
  validates_presence_of :envolved_school, presence: true, message: 'can t be left blank'
  validates_presence_of :envolved_family, presence: true, message: 'can t be left blank'
  validates_presence_of :envolved_student, presence: true, message: 'can t be left blank'
  validates_presence_of :realized_actions, presence: true, message: 'can t be left blank'
  validates_presence_of :possibly_saa, presence: true, message: 'can t be left blank'
  validates_presence_of :possibly_eeaa, presence: true, message: 'can t be left blank'
  validates_presence_of :possibly_resources, presence: true, message: 'can t be left blank'
  validates_presence_of :possibly_adequation, presence: true, message: 'can t be left blank'

end
