class Report < ApplicationRecord
  belongs_to :student

  validates_presence_of :init_date, presence: true, message: 'can t be left blank'
  validates_presence_of :end_date, presence: true, message: 'can t be left blank'
  validates_presence_of :school_phone, presence: true, message: 'can t be left blank'
  validates_presence_of :member_name, presence: true, message: 'can t be left blank'
  validates_presence_of :school_name, presence: true, message: 'can t be left blank'
  validates_presence_of :reason, presence: true, message: 'can t be left blank'
  validates_presence_of :general_information, presence: true, message: 'can t be left blank'
  validates_presence_of :synthesis, presence: true, message: 'can t be left blank'
  validates_presence_of :conclusion, presence: true, message: 'can t be left blank'
  validates_presence_of :family_orientation, presence: true, message: 'can t be left blank'
  validates_presence_of :school_orientation, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_name, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_function, presence: true, message: 'can t be left blank'
  validates_presence_of :pedagogue_registry, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_name, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_function, presence: true, message: 'can t be left blank'
  validates_presence_of :psycholog_registry, presence: true, message: 'can t be left blank'
  validates_inclusion_of :reason_adequation, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :reason_emotional, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :reason_performance, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :reason_behavior, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :reason_language, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :level_school, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :level_family, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :level_student, :in => [true, false], message: 'can t be left blank'
  validates_presence_of :envolved_school, presence: true, message: 'can t be left blank'
  validates_presence_of :envolved_family, presence: true, message: 'can t be left blank'
  validates_presence_of :envolved_student, presence: true, message: 'can t be left blank'
  validates_presence_of :realized_actions, presence: true, message: 'can t be left blank'
  validates_inclusion_of :possibly_saa, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :possibly_eeaa, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :possibly_resources, :in => [true, false], message: 'can t be left blank'
  validates_inclusion_of :possibly_adequation, :in => [true, false], message: 'can t be left blank'
  validates_presence_of :created_by, presence: true, message: 'can t be left blank'
  validates_presence_of :updated_by, presence: true, message: 'can t be left blank'
end
